version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
    - echo Logging into Amazon ECR
    - aws --version
    - $(aws ecr get-login --no-include-mail --region us-west-2)
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
    - REPOSITORY_URI={URI}
  build:
    commands:
    - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
    - echo Build started on `date`
    - echo Building the Docker image... 
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
    - echo Build completed on `date`
    - echo pushing to repo
    - docker push $REPOSITORY_URI:latest
    - echo Writing image definitions file. . .
    - printf '[{"name": "dummy_service", "imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json